---
- name: Harden production Linux server
  hosts: linux_servers
  become: true

  tasks:

    - name: Update installed packages
      ansible.builtin.dnf:
        name: "*"
        state: latest

    - name: Install administration packages
      ansible.builtin.dnf:
        name:
          - vim
        state: present