---
- name: Harden production Linux server
  hosts: linux_servers
  become: true

  tasks:

    - name: Update installed packages
      ansible.builtin.dnf:
        name: "*"
        state: latest

    - name: Install security and administration packages
      ansible.builtin.dnf:
        name:
          - vim
          - rsyslog
          - firewalld
        state: present

    - name: Ensure rsyslog is enabled and running
      ansible.builtin.service:
        name: rsyslog
        state: started
        enabled: true